#!/bin/bash

COMPOSER_FILE_PREV_DIR=$(pwd)
COMPOSER_FILE_DIR=$(dirname ${BASH_SOURCE[0]});
cd $COMPOSER_FILE_DIR;
COMPOSER_FILE_DIR=$(pwd)

docker compose -f "docker-compose.yml" exec -it -u developer app php artisan "${@:1}"

cd $COMPOSER_FILE_PREV_DIR;
