services:
    app:
        container_name: camlapse
        hostname: camlapse
        image: camlapse:latest
        privileged: true
        healthcheck:
            test: curl --fail --header 'Host:camlapse.world' http://127.0.0.1 || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        build:
            target: $build_stage
            context: .
            dockerfile: docker/Dockerfile
            args:
                - UID=$USERID
                - GID
        volumes:
            - .:/srv
            - camlapse_database_data:/database
            - camlapse_timelapse_data:/srv/public/timelapse
        ports:
            - 80:80
        expose:
            - 9000
        networks:
            - camlapse_frontend
            - camlapse_backend

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - camlapse_redis_data:/data
        command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
        mem_limit: 256M
        cpus: "0.5"
        networks:
            - camlapse_backend

volumes:
    camlapse_redis_data:
        external: true
    camlapse_database_data:
        external: true
    camlapse_timelapse_data:
        external: true

networks:
    camlapse_frontend:
        external: true
    camlapse_backend:
        external: true
