services:
    app:
        container_name: camlapse
        hostname: camlapse
        image: camlapse:latest
        privileged: true
        healthcheck:
            test: curl --fail --header 'Host:camlapse.world' http://127.0.0.1 || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        build:
            target: $build_stage
            context: .
            dockerfile: docker/Dockerfile
            args:
                - UID=$USERID
                - GID
        volumes:
            - .:/srv
        ports:
            - 80:80
        expose:
            - 9000
        networks:
            - frontend
            - backend

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
        mem_limit: 256M
        cpus: "0.5"
        networks:
            - backend

volumes:
    redis_data:

networks:
    frontend:
    backend:
