services:
    app:
        container_name: camlapse
        hostname: camlapse
        privileged: true
        healthcheck:
            test: curl --fail --header 'Host:camlapse.world' http://127.0.0.1 || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                - UID=$USERID
                - GID
        volumes:
            - .:/srv
        ports:
            - 80:80
        expose:
            - 9000
