#!/bin/bash

export USERID=$(id -u)
export GID=$(id -g)
export build_stage=${build_stage:-dev}
password=$(cat)

echo $password | sudo -S -k -E docker compose -f docker-compose.$build_stage.yml "${@:1}";
