#!/usr/bin/env bash

# make current script invokable from any directory
CONSTANTS_FILE_PREV_DIR=$(pwd)
CONSTANTS_FILE_DIR=$(dirname ${BASH_SOURCE[0]});
cd $CONSTANTS_FILE_DIR;
CONSTANTS_FILE_DIR=$(pwd)

##################################################################

APP_NAME="CamLapse"
app_name="$(echo "$APP_NAME" | tr '[A-Z]' '[a-z]')"

OWNERS_EMAIL=danekkatz@gmail.com
DOMAIN=camlapse
DOMAIN_QA=camlapse
DOMAIN_LOCAL=camlapse

URL_PROD=${DOMAIN}.world
URL_QA=${DOMAIN_QA}.world
URL_DEV=${DOMAIN_LOCAL}.world
URL=$URL_PROD

DOCKER_COMPOSE_FILE="docker-compose.yml";

TARGET=prod

# APP_ENV MUST be one of local|testing|production because of laravel framework
APP_ENV="production"

ENV=${1:-DEV}

if [ "$ENV" = "DEV" ]; then
  ENV="DEV";
  URL=$URL_DEV
  TARGET=dev
  APP_ENV=local
else
  if [ "$ENV" = "QA" ]; then
    ENV="QA";
    URL=$URL_QA
  else
    ENV="PROD";
  fi;
fi;

# lowercase
env="$(echo "$ENV" | tr '[A-Z]' '[a-z]')"

# COMPOSE_IGNORE_ORPHANS=true;

WEB_HOST=camlapse_$env

export UID
export GID=$(id -g)

. ./dirs_$env;

cd $CONSTANTS_FILE_PREV_DIR;
